"""Autogenerate votes table 2

Revision ID: a5a0d0cf0944
Revises: eb02a8480b95
Create Date: 2022-07-21 20:16:38.685343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a0d0cf0944'
down_revision = 'eb02a8480b95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
